/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 tile2_7_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function T1(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` + 'tile2_7_opt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_2.geometry} material={materials.Tile_2_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_3_1.geometry} material={materials.Tile_3_0} />
        <mesh geometry={nodes.Tile_3_2.geometry} material={materials.Tile_3_1} />
      </group>
      <mesh geometry={nodes.Tile_4.geometry} material={materials.Tile_4_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_5.geometry} material={materials.Tile_5_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_6.geometry} material={materials.Tile_6_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_7.geometry} material={materials.Tile_7_0} position={[0, -70, 0]} />
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'tile2_7_opt.glb')
