/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 tile17_24_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../../config'

export function M3(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` +'tile17_24.glb')
  return (
    <group {...props} dispose={null}
    >
      <mesh geometry={nodes.Tile_17.geometry} material={materials['Tile_17_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_18.geometry} material={materials['Tile_18_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_19.geometry} material={materials['Tile_19_0.001']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_20001.geometry} material={materials['Tile_20_0.001']} />
        <mesh geometry={nodes.Tile_20001_1.geometry} material={materials['Tile_20_1.001']} />
      </group>
      <mesh geometry={nodes.Tile_21.geometry} material={materials['Tile_21_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_22.geometry} material={materials['Tile_22_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_23.geometry} material={materials['Tile_23_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_24.geometry} material={materials['material_0.001']} position={[0, -70, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` +'tile17_24.glb')
