/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 tile25_31_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../../config'

export function M4(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` +'tile25_31_opt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_25.geometry} material={materials.Tile_25_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_27.geometry} material={materials.Tile_27_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_28.geometry} material={materials.Tile_28_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_29.geometry} material={materials.Tile_29_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_30_1.geometry} material={materials.Tile_30_0} />
        <mesh geometry={nodes.Tile_30_2.geometry} material={materials.Tile_30_1} />
      </group>
      <mesh geometry={nodes.Tile_31.geometry} material={materials.Tile_31_0} position={[0, -70, 0]} />
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` +'tile25_31_opt.glb')
