/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 C2_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function C2(props) {
  const { nodes, materials } = useGLTF('/C2_opt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_18001.geometry} material={materials['Tile_18_1.002']} />
      <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />

    </group>
  )
}

useGLTF.preload('/C2_opt.glb')
