<<<<<<< HEAD:src/M1_M2/C3_opt.jsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 C3_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { modelPath } from '../config'

export function C3(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` + 'C3_opt.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_18002.geometry} material={materials['Tile_18_0.003']} onClick={(e) => console.log(e.point)}>
        <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />
      </mesh>
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'C3_opt.glb')
=======
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 crack_3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { modelPath }from '../config'

export function C3(props) {

  const { nodes, materials } = useGLTF( `/${modelPath}/` +'crack_3.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_18002.geometry} material={materials['Tile_18_0.003']}
            onClick={(e) =>
              console.log(e.point)
            }
      >
        <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />
      </mesh>

    </group>
  )
}

useGLTF.preload( `/${modelPath}/` +'crack_3.glb')
>>>>>>> 20e472be9f1ef4c3ddb4ee219f739f2a26fe24c6:src/M1_M2/crack3.jsx
