/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/m1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}` +'m1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_2.geometry} material={materials.Tile_2_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_3_1.geometry} material={materials.Tile_3_0} />
        <mesh geometry={nodes.Tile_3_2.geometry} material={materials.Tile_3_1} />
      </group>
      <mesh geometry={nodes.Tile_4.geometry} material={materials.Tile_4_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_5.geometry} material={materials.Tile_5_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_6.geometry} material={materials.Tile_6_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_7.geometry} material={materials.Tile_7_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_8_1.geometry} material={materials.Tile_8_0} />
        <mesh geometry={nodes.Tile_8_2.geometry} material={materials.Tile_8_1} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_9_1.geometry} material={materials.Tile_9_0} />
        <mesh geometry={nodes.Tile_9_2.geometry} material={materials.Tile_9_1} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_10_1.geometry} material={materials.Tile_10_0} />
        <mesh geometry={nodes.Tile_10_2.geometry} material={materials.Tile_10_1} />
      </group>
      <mesh geometry={nodes.Tile_11.geometry} material={materials.Tile_11_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_12.geometry} material={materials.Tile_12_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_13.geometry} material={materials.Tile_13_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_9002.geometry} material={materials['Tile_9_0.002']} />
        <mesh geometry={nodes.Tile_9002_1.geometry} material={materials['Tile_9_1.002']} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_8003.geometry} material={materials['Tile_8_0.003']} />
        <mesh geometry={nodes.Tile_8003_1.geometry} material={materials['Tile_8_1.003']} />
      </group>
      <mesh geometry={nodes.Tile_7001.geometry} material={materials['Tile_7_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_6001.geometry} material={materials['Tile_6_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_5001.geometry} material={materials['Tile_5_0.003']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_4003.geometry} material={materials['Tile_4_0.003']} />
        <mesh geometry={nodes.Tile_4003_1.geometry} material={materials['Tile_4_1.003']} />
        <mesh geometry={nodes.Tile_4003_2.geometry} material={materials['Tile_4_2.003']} />
      </group>
      <mesh geometry={nodes.Tile_36001.geometry} material={materials['Tile_36_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_35001.geometry} material={materials['Tile_35_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_34001.geometry} material={materials['Tile_34_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_30001.geometry} material={materials['Tile_30_0.002']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_3001.geometry} material={materials['Tile_3_0.003']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_29002.geometry} material={materials['Tile_29_1.002']} />
        <mesh geometry={nodes.Tile_29002_1.geometry} material={materials['Tile_29_0.002']} />
      </group>
      <mesh geometry={nodes.Tile_28001.geometry} material={materials['Tile_28_0.002']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_27003.geometry} material={materials['Tile_27_0.003']} />
        <mesh geometry={nodes.Tile_27003_1.geometry} material={materials['Tile_27_1.003']} />
      </group>
      <mesh geometry={nodes.Tile_26001.geometry} material={materials['Tile_26_0.002']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_25001.geometry} material={materials['Tile_25_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_16001.geometry} material={materials['Tile_16_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_15.geometry} material={materials['Tile_15_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_14.geometry} material={materials['Tile_14_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_10001.geometry} material={materials['Tile_10_0.002']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_37.geometry} material={materials['Tile_37_0.002']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_38.geometry} material={materials['Tile_38_0.003']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_39002.geometry} material={materials['Tile_39_0.002']} />
        <mesh geometry={nodes.Tile_39002_1.geometry} material={materials['Tile_39_1.002']} />
        <mesh geometry={nodes.Tile_39002_2.geometry} material={materials['Tile_39_2.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/m1.glb')
