/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 M1_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { modelPath }from '../config'


export function M1(props) {

      const path = `/${modelPath}/` +'M1_opt.glb'
      console.log('path:', path);

      const { nodes, materials } = useGLTF(`/${modelPath}/` +'M1_opt.glb')

    return (
      <group {...props} dispose={null}>
          <mesh geometry={nodes.Tile_7.geometry} material={materials['Tile_7_0.002']} />
          <mesh geometry={nodes.Tile_6.geometry} material={materials['Tile_6_0.002']} />
          <mesh geometry={nodes.Tile_5.geometry} material={materials['Tile_5_0.002']} />
          <mesh geometry={nodes.Tile_36001.geometry} material={materials['Tile_36_0.001']} />
          <mesh geometry={nodes.Tile_35001.geometry} material={materials['Tile_35_0.001']} />
          <mesh geometry={nodes.Tile_34001.geometry} material={materials['Tile_34_0.001']} />
          <mesh geometry={nodes.Tile_30001.geometry} material={materials['Tile_30_0.003']} />
          <mesh geometry={nodes.Tile_3.geometry} material={materials['Tile_3_0.002']} />
          <mesh geometry={nodes.Tile_28001.geometry} material={materials['Tile_28_0.003']} />
          <mesh geometry={nodes.Tile_26001.geometry} material={materials['Tile_26_0.003']} />
          <mesh geometry={nodes.Tile_25001.geometry} material={materials['Tile_25_0.002']} />
          <mesh geometry={nodes.Tile_16001.geometry} material={materials['Tile_16_0.002']} />
          <mesh geometry={nodes.Tile_15.geometry} material={materials['Tile_15_0.002']} />
          <mesh geometry={nodes.Tile_14.geometry} material={materials['Tile_14_0.002']} />
          <mesh geometry={nodes.Tile_10.geometry} material={materials['Tile_10_0.003']} />
          <mesh geometry={nodes.Tile_37.geometry} material={materials.Tile_37_0} />
          <mesh geometry={nodes.Tile_38.geometry} material={materials['Tile_38_0.001']} />
          <mesh geometry={nodes.Tile_9003.geometry} material={materials['Tile_9_0.003']} />
          <mesh geometry={nodes.Tile_9003_1.geometry} material={materials['Tile_9_1.003']} />
          <mesh geometry={nodes.Tile_8002.geometry} material={materials['Tile_8_0.002']} />
          <mesh geometry={nodes.Tile_8002_1.geometry} material={materials['Tile_8_1.002']} />
          <mesh geometry={nodes.Tile_4002.geometry} material={materials['Tile_4_0.002']} />
          <mesh geometry={nodes.Tile_4002_1.geometry} material={materials['Tile_4_1.002']} />
          <mesh geometry={nodes.Tile_4002_2.geometry} material={materials['Tile_4_2.002']} />
          <mesh geometry={nodes.Tile_29005.geometry} material={materials['Tile_29_0.003']} />
          <mesh geometry={nodes.Tile_29005_1.geometry} material={materials['Tile_29_1.003']} />
          <mesh geometry={nodes.Tile_27002.geometry} material={materials['Tile_27_0.002']} />
          <mesh geometry={nodes.Tile_27002_1.geometry} material={materials['Tile_27_1.002']} />
          <mesh geometry={nodes.Tile_39_1.geometry} material={materials.Tile_39_0} />
          <mesh geometry={nodes.Tile_39_2.geometry} material={materials.Tile_39_1} />
          <mesh geometry={nodes.Tile_39_3.geometry} material={materials.Tile_39_2} />
      </group>
    )
}

useGLTF.preload( `/${modelPath}/` +'M1_opt.glb')