/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 test_2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` + 'test_2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-18.605, 10.831, -6.37]} rotation={[-1.583, 0.093, -0.388]} scale={[0.77, 1.91, 1.04]}>

        <mesh
          onClick={(e) => {
            console.log(e.point)
          }}
          geometry={nodes.Rectangle001.geometry} material={materials['Material__43.002']} scale={0.025}  >
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + '/test_2.glb')
