/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 test_3.glb --transform 
Files: test_3.glb [4.21KB] > test_3-transformed.glb [1.6KB] (62%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test_3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={(e) => {
          // showPopup(image_filename, problemAreaId)
          console.log(e.point)
        }}
        geometry={nodes.Box001.geometry}
        material={materials.Material__43}
        position={[-29.699, 20.984, -14.934]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.025, 0.034, 0.048]}
      />
    </group>
  )
}

useGLTF.preload('/test_3-transformed.glb')
