/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 tile17_24_opt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T3(props) {
  const { nodes, materials } = useGLTF('/tile17_24_opt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_17.geometry} material={materials.Tile_17_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_18.geometry} material={materials.Tile_18_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_19.geometry} material={materials.Tile_19_0} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_20_1.geometry} material={materials.Tile_20_0} />
        <mesh geometry={nodes.Tile_20_2.geometry} material={materials.Tile_20_1} />
      </group>
      <mesh geometry={nodes.Tile_21.geometry} material={materials.Tile_21_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_22.geometry} material={materials.Tile_22_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_23.geometry} material={materials.Tile_23_0} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_24.geometry} material={materials.Tile_24_0} position={[0, -70, 0]} />
    </group>
  )
}

useGLTF.preload('/tile17_24_opt.glb')
