/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE3.glb --output ./jsx/TREE3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[14.51, 6.39, -20.22]} rotation={[-0.714, 0.506, 0.12]} scale={[1.44, 1.31, 0.68]}>
        <mesh geometry={nodes['33002_1'].geometry} material={materials['material_0.002']} />
        <mesh geometry={nodes['33002_2'].geometry} material={materials['material_1.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE3.glb')
