/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE4.glb --output ./jsx/TREE4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE4.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[18.15, 9.04, -29.12]} rotation={[-0.12, 0.516, -0.064]} scale={[1.16, 1.62, 1.16]}>
        <mesh geometry={nodes['33003_1'].geometry} material={materials['material_0.003']} />
        <mesh geometry={nodes['33003_2'].geometry} material={materials['material_1.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE4.glb')
