/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE7.glb --output ./jsx/TREE7.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE7.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.68, 6.7, 38.24]} rotation={[-0.512, -1.3, -1.22]} scale={[1.23, 1.06, 1.06]}>
        <mesh geometry={nodes['33006_1'].geometry} material={materials['material_0.006']} />
        <mesh geometry={nodes['33006_2'].geometry} material={materials['material_1.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE7.glb')
