/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE6.glb --output ./jsx/TREE6.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE6.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-13.52, 9.01, 31.96]} rotation={[-1.155, -1.111, -1.419]}>
        <mesh geometry={nodes['33005_1'].geometry} material={materials['material_0.005']} />
        <mesh geometry={nodes['33005_2'].geometry} material={materials['material_1.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE6.glb')
