/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE1.glb --output ./jsx/TREE1.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[6.17, 4.22, 16.9]} rotation={[-1.117, 1.182, 0.993]} scale={[1.38, 1.35, 0.97]}>
        <mesh geometry={nodes['33_1'].geometry} material={materials.material_0} />
        <mesh geometry={nodes['33_2'].geometry} material={materials.material_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE1.glb')
