/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/TREE2.glb --output ./jsx/TREE2.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TREE2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[11.52, 5.53, -12.26]} rotation={[-0.386, -0.309, -0.123]} scale={[1.11, 1.26, 1.2]}>
        <mesh geometry={nodes['33001_1'].geometry} material={materials['material_0.001']} />
        <mesh geometry={nodes['33001_2'].geometry} material={materials['material_1.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TREE2.glb')
