/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./output/m10_13.glb --output ./jsx/m10_13.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/m10_13.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Tile_10" position={[0, -70, 0]}>
          <mesh name="메쉬033" geometry={nodes.메쉬033.geometry} material={materials.Tile_10_0} />
          <mesh name="메쉬033_1" geometry={nodes.메쉬033_1.geometry} material={materials.Tile_10_0} />
        </group>
        <mesh name="Tile_11" geometry={nodes.Tile_11.geometry} material={materials.Tile_10_0} position={[0, -70, 0]} />
        <mesh name="Tile_12" geometry={nodes.Tile_12.geometry} material={materials.Tile_10_0} position={[0, -70, 0]} />
        <mesh name="Tile_13" geometry={nodes.Tile_13.geometry} material={materials.Tile_10_0} position={[0, -70, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/m10_13.glb')
