/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./output/m14_17.glb --output ./jsx/m14_17.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/m14_17.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Tile_14" position={[0, -70, 0]}>
          <mesh name="메쉬037" geometry={nodes.메쉬037.geometry} material={materials.Tile_14_0} />
          <mesh name="메쉬037_1" geometry={nodes.메쉬037_1.geometry} material={materials.Tile_14_0} />
        </group>
        <mesh name="Tile_15" geometry={nodes.Tile_15.geometry} material={materials.Tile_14_0} position={[0, -70, 0]} />
        <mesh name="Tile_16" geometry={nodes.Tile_16.geometry} material={materials.Tile_14_0} position={[0, -70, 0]} />
        <mesh name="Tile_17" geometry={nodes.Tile_17.geometry} material={materials.Tile_14_0} position={[0, -70, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/m14_17.glb')
