/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./output/m27_31.glb --output ./jsx/m27_31.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/m27_31.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Tile_27" geometry={nodes.Tile_27.geometry} material={materials.Tile_27_0} position={[0, -70, 0]} />
        <mesh name="Tile_28" geometry={nodes.Tile_28.geometry} material={materials.Tile_27_0} position={[0, -70, 0]} />
        <mesh name="Tile_29" geometry={nodes.Tile_29.geometry} material={materials.Tile_27_0} position={[0, -70, 0]} />
        <group name="Tile_30" position={[0, -70, 0]}>
          <mesh name="메쉬052" geometry={nodes.메쉬052.geometry} material={materials.Tile_27_0} />
          <mesh name="메쉬052_1" geometry={nodes.메쉬052_1.geometry} material={materials.Tile_27_0} />
        </group>
        <mesh name="Tile_31" geometry={nodes.Tile_31.geometry} material={materials.Tile_27_0} position={[0, -70, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/m27_31.glb')
