/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./output/m2_5.glb --output ./jsx/m2_5.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/m2_5.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Tile_2" geometry={nodes.Tile_2.geometry} material={materials.Tile_2_0} position={[0, -70, 0]} />
        <group name="Tile_3" position={[0, -70, 0]}>
          <mesh name="메쉬026" geometry={nodes.메쉬026.geometry} material={materials.Tile_2_0} />
          <mesh name="메쉬026_1" geometry={nodes.메쉬026_1.geometry} material={materials.Tile_2_0} />
        </group>
        <mesh name="Tile_4" geometry={nodes.Tile_4.geometry} material={materials.Tile_2_0} position={[0, -70, 0]} />
        <mesh name="Tile_5" geometry={nodes.Tile_5.geometry} material={materials.Tile_2_0} position={[0, -70, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/m2_5.glb')
