/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/tilee5.glb --output ./jsx/tilee5.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tilee5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-11.253, 21.43, 1.647]} rotation={[Math.PI / 2, 0, -1.623]}>
        <mesh geometry={nodes.tile004_1.geometry} material={materials['material_0.004']} />
        <mesh geometry={nodes.tile004_2.geometry} material={materials['material_1.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tilee5.glb')
