/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/tilee4.glb --output ./jsx/tilee4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tilee4.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.967, 21.358, 4.235]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.tile003_1.geometry} material={materials['material_0.003']} />
        <mesh geometry={nodes.tile003_2.geometry} material={materials['material_1.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tilee4.glb')
