/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/tilee3.glb --output ./jsx/tilee3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tilee3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.213, 18.939, 3.753]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.tile002_1.geometry} material={materials['material_0.002']} />
        <mesh geometry={nodes.tile002_2.geometry} material={materials['material_1.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tilee3.glb')
