/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 all_edited.glb --transform 
Files: all_edited.glb [7.61MB] > all_edited-transformed.glb [2.3MB] (70%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/all_edited-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_1.geometry} material={materials.Material_0} position={[0.283, 5.274, 1.352]} />
    </group>
  )
}

useGLTF.preload('/all_edited-transformed.glb')
