/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/111.glb --output ./jsx/111.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/111.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tiie2.geometry} material={materials['material_0.022']} position={[-18.453, 13.702, -4.346]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/111.glb')
