/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/222.glb --output ./jsx/222.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/222.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tiie2001.geometry} material={materials['material_0.023']} position={[8.542, 19.77, -12.586]} rotation={[Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/222.glb')
