/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 c2_m1.glb --transform 
Files: c2_m1.glb [8.45MB] > c2_m1-transformed.glb [251.8KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { C1 } from './C1_m1'
import * as THREE from 'three'

export function C2(props) {
  const { nodes, materials } = useGLTF('/c2_m1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_18002.geometry} material={materials['Tile_18_0.002']} />
      <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />

    </group>
  )
}

useGLTF.preload('/c2_m1-transformed.glb')
