/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 c3_m2.glb --transform 
Files: c3_m2.glb [4.97MB] > c3_m2-transformed.glb [134.54KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { C1 } from './C1_m1'
import * as THREE from 'three'

export function C3(props) {
  const { nodes, materials } = useGLTF('/c3_m2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_31001.geometry} material={materials.Tile_31_0} />
      <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />

    </group>
  )
}

useGLTF.preload('/c3_m2-transformed.glb')
