/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 c4_m3.glb --transform 
Files: c4_m3.glb [5.61MB] > c4_m3-transformed.glb [201.7KB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { C1 } from './C1_m1'
import * as THREE from 'three'

export function C4(props) {
  const { nodes, materials } = useGLTF('/c4_m3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_26001.geometry} material={materials['Tile_26_0.001']} />
      <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />

    </group>
  )
}

useGLTF.preload('/c4_m3-transformed.glb')
