/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 c5_m4.glb --transform 
Files: c5_m4.glb [6.53MB] > c5_m4-transformed.glb [210.04KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function C5(props) {
  const { nodes, materials } = useGLTF('/c5_m4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_29001.geometry} material={materials['Tile_29_0.001']} />
      <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />

    </group>
  )
}

useGLTF.preload('/c5_m4-transformed.glb')
