/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 m1.glb --transform 
Files: m1.glb [689.2MB] > m1-transformed.glb [57.78MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function M1(props) {
  const { nodes, materials } = useGLTF('/m1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_33.geometry} material={materials['Tile_33_0.001']} />
      <mesh geometry={nodes.Tile_3.geometry} material={materials['Tile_3_0.001']} />
      <mesh geometry={nodes.Tile_24.geometry} material={materials['Tile_24_0.001']} />
      <mesh geometry={nodes.Tile_23.geometry} material={materials['Tile_23_0.001']} />
      <mesh geometry={nodes.Tile_19.geometry} material={materials['Tile_19_0.001']} />
      <mesh geometry={nodes.Tile_17.geometry} material={materials['Tile_17_0.001']} />
      <mesh geometry={nodes.Tile_12.geometry} material={materials['Tile_12_0.001']} />
      <mesh geometry={nodes.Tile_11.geometry} material={materials['Tile_11_0.001']} />
      <mesh geometry={nodes.Tile_1.geometry} material={materials['Tile_1_0.004']} />
      <mesh geometry={nodes.Tile_4001.geometry} material={materials['Tile_4_0.001']} />
      <mesh geometry={nodes.Tile_4001_1.geometry} material={materials['Tile_4_1.001']} />
      <mesh geometry={nodes.Tile_4001_2.geometry} material={materials['Tile_4_2.001']} />
      <mesh geometry={nodes.Tile_2002.geometry} material={materials['Tile_2_0.002']} />
      <mesh geometry={nodes.Tile_2002_1.geometry} material={materials['Tile_2_1.002']} />
      <mesh geometry={nodes.Tile_18001.geometry} material={materials['Tile_18_0.001']} />
      <mesh geometry={nodes.Tile_18001_1.geometry} material={materials['Tile_18_1.001']} />
      <mesh geometry={nodes.Tile_13001.geometry} material={materials['Tile_13_0.001']} />
      <mesh geometry={nodes.Tile_13001_1.geometry} material={materials['Tile_13_1.001']} />
    </group>
  )
}

useGLTF.preload('/m1-transformed.glb')
