/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 m2.glb --transform 
Files: m2.glb [184.59MB] > m2-transformed.glb [15.04MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function M2(props) {
  const { nodes, materials } = useGLTF('/m2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_32.geometry} material={materials.Tile_32_0} />
      <mesh geometry={nodes.Tile_31.geometry} material={materials.Tile_31_0} />
      <mesh geometry={nodes.Tile_22.geometry} material={materials['Tile_22_0.001']} />
      <mesh geometry={nodes.Tile_21.geometry} material={materials['Tile_21_0.001']} />
      <mesh geometry={nodes.Tile_20.geometry} material={materials['Tile_20_0.001']} />
    </group>
  )
}

useGLTF.preload('/m2-transformed.glb')
