/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 m3.glb --transform 
Files: m3.glb [583.59MB] > m3-transformed.glb [49.01MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function M3(props) {
  const { nodes, materials } = useGLTF('/m3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_7.geometry} material={materials['Tile_7_0.001']} />
      <mesh geometry={nodes.Tile_6.geometry} material={materials['Tile_6_0.001']} />
      <mesh geometry={nodes.Tile_5.geometry} material={materials['Tile_5_0.001']} />
      <mesh geometry={nodes.Tile_36.geometry} material={materials.Tile_36_0} />
      <mesh geometry={nodes.Tile_35.geometry} material={materials.Tile_35_0} />
      <mesh geometry={nodes.Tile_34.geometry} material={materials.Tile_34_0} />
      <mesh geometry={nodes.Tile_26.geometry} material={materials['Tile_26_0.001']} />
      <mesh geometry={nodes.Tile_25.geometry} material={materials['Tile_25_0.001']} />
      <mesh geometry={nodes.Tile_16.geometry} material={materials['Tile_16_0.001']} />
      <mesh geometry={nodes.Tile_15.geometry} material={materials['Tile_15_0.001']} />
      <mesh geometry={nodes.Tile_14.geometry} material={materials['Tile_14_0.001']} />
      <mesh geometry={nodes.Tile_8001.geometry} material={materials['Tile_8_0.001']} />
      <mesh geometry={nodes.Tile_8001_1.geometry} material={materials['Tile_8_1.001']} />
      <mesh geometry={nodes.Tile_27001.geometry} material={materials['Tile_27_0.001']} />
      <mesh geometry={nodes.Tile_27001_1.geometry} material={materials['Tile_27_1.001']} />
    </group>
  )
}

useGLTF.preload('/m3-transformed.glb')
