/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 m4.glb --transform 
Files: m4.glb [393.88MB] > m4-transformed.glb [35.09MB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function M4(props) {
  const { nodes, materials } = useGLTF('/m4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_30.geometry} material={materials['Tile_30_0.001']} />
      <mesh geometry={nodes.Tile_28.geometry} material={materials['Tile_28_0.001']} />
      <mesh geometry={nodes.Tile_10.geometry} material={materials['Tile_10_0.001']} />
      <mesh geometry={nodes.Tile_9001.geometry} material={materials['Tile_9_0.001']} />
      <mesh geometry={nodes.Tile_9001_1.geometry} material={materials['Tile_9_1.001']} />
      <mesh geometry={nodes.Tile_29001.geometry} material={materials['Tile_29_0.001']} />
      <mesh geometry={nodes.Tile_29001_1.geometry} material={materials['Tile_29_1.001']} />
    </group>
  )
}

useGLTF.preload('/m4-transformed.glb')
