/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/M1.glb --output ./jsx/M1.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` +'M1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_2.geometry} material={materials['Tile_2_0.004']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_3004.geometry} material={materials['Tile_3_0.004']} />
        <mesh geometry={nodes.Tile_3004_1.geometry} material={materials['Tile_3_1.004']} />
      </group>
      <mesh geometry={nodes.Tile_4.geometry} material={materials['Tile_4_0.004']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_5.geometry} material={materials['Tile_5_0.004']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_6.geometry} material={materials['Tile_6_0.003']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_7.geometry} material={materials['Tile_7_0.003']} position={[0, -70, 0]} />
    </group>
  )
}


useGLTF.preload(`/${modelPath}/` + 'M1.glb')

