/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/M2.glb --output ./jsx/M2.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}` +'/M2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_8.geometry} material={materials['Tile_8_0.002']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_9.geometry} material={materials['Tile_9_0.002']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_10002.geometry} material={materials['Tile_10_0.002']} />
        <mesh geometry={nodes.Tile_10002_1.geometry} material={materials['Tile_10_1.002']} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_11002.geometry} material={materials['Tile_11_0.002']} />
        <mesh geometry={nodes.Tile_11002_1.geometry} material={materials['Tile_11_1.002']} />
      </group>
      <mesh geometry={nodes.Tile_12.geometry} material={materials['Tile_12_0.002']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_13002.geometry} material={materials['Tile_13_0.002']} />
        <mesh geometry={nodes.Tile_13002_1.geometry} material={materials['Tile_13_1.002']} />
      </group>
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'M2.glb')
