/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/M3.glb --output ./jsx/M3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}` +'/M3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_14002.geometry} material={materials['Tile_14_0.002']} />
        <mesh geometry={nodes.Tile_14002_1.geometry} material={materials['Tile_14_1.002']} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_15002.geometry} material={materials['Tile_15_0.002']} />
        <mesh geometry={nodes.Tile_15002_1.geometry} material={materials['Tile_15_1.002']} />
      </group>
      <mesh geometry={nodes.Tile_16.geometry} material={materials['Tile_16_0.001']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_17001.geometry} material={materials['Tile_17_0.001']} />
        <mesh geometry={nodes.Tile_17001_1.geometry} material={materials['Tile_17_1.001']} />
      </group>
      <mesh geometry={nodes.Tile_18.geometry} material={materials['Tile_18_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_19.geometry} material={materials['Tile_19_0.001']} position={[0, -70, 0]} />
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'M3.glb')
