/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/M4.glb --output ./jsx/M4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}` +'/M4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_20.geometry} material={materials['Tile_20_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_21.geometry} material={materials['Tile_21_0.001']} position={[0, -70, 0]} />
      <mesh geometry={nodes.Tile_22.geometry} material={materials['Tile_22_0.001']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_23001.geometry} material={materials['Tile_23_0.001']} />
        <mesh geometry={nodes.Tile_23001_1.geometry} material={materials['Tile_23_1.001']} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_24001.geometry} material={materials['Tile_24_0.001']} />
        <mesh geometry={nodes.Tile_24001_1.geometry} material={materials['Tile_24_1.001']} />
      </group>
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_25001.geometry} material={materials['Tile_25_0.001']} />
        <mesh geometry={nodes.Tile_25001_1.geometry} material={materials['Tile_25_1.001']} />
      </group>
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'M4.glb')
