/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/M6.glb --output ./jsx/M6.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelPath } from '../config'

export function Model(props) {
  const { nodes, materials } = useGLTF(`/${modelPath}` +'/M6.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_32.geometry} material={materials['Tile_32_0.001']} position={[0, -70, 0]} />
      <group position={[0, -70, 0]}>
        <mesh geometry={nodes.Tile_33001.geometry} material={materials['Tile_33_0.001']} />
        <mesh geometry={nodes.Tile_33001_1.geometry} material={materials['Tile_33_1.001']} />
      </group>
      <mesh geometry={nodes.Tile_34.geometry} material={materials['Tile_34_0.001']} position={[0, -70, 0]} />
    </group>
  )
}

useGLTF.preload(`/${modelPath}/` + 'M6.glb')
