/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t11_15.glb --transform 
Files: t11_15.glb [183.57MB] > t11_15-transformed.glb [15.31MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T11_15(props) {
  const { nodes, materials } = useGLTF('/t11_15-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_11.geometry} material={materials.Tile_11_0} />
      <mesh geometry={nodes.Tile_12.geometry} material={materials.Tile_12_0} />
      <mesh geometry={nodes.Tile_14.geometry} material={materials.Tile_14_0} />
      <mesh geometry={nodes.Tile_15.geometry} material={materials.Tile_15_0} />
      <mesh geometry={nodes.Tile_13_1.geometry} material={materials.Tile_13_0} />
      <mesh geometry={nodes.Tile_13_2.geometry} material={materials.Tile_13_1} />
    </group>
  )
}

useGLTF.preload('/t11_15-transformed.glb')
