/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t16_20.glb --transform 
Files: t16_20.glb [278.55MB] > t16_20-transformed.glb [23.18MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T16_20(props) {
  const { nodes, materials } = useGLTF('/t16_20-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_16.geometry} material={materials.Tile_16_0} />
      <mesh geometry={nodes.Tile_17.geometry} material={materials.Tile_17_0} />
      <mesh geometry={nodes.Tile_19.geometry} material={materials.Tile_19_0} />
      <mesh geometry={nodes.Tile_20.geometry} material={materials.Tile_20_0} />
      <mesh geometry={nodes.Tile_18_1.geometry} material={materials.Tile_18_0} />
      <mesh geometry={nodes.Tile_18_2.geometry} material={materials.Tile_18_1} />
    </group>
  )
}

useGLTF.preload('/t16_20-transformed.glb')
