/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t1_5.glb --tranform 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T1_5(props) {
  const { nodes, materials } = useGLTF('/t1_5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_1.geometry} material={materials.Tile_1_0} />
      <mesh geometry={nodes.Tile_3.geometry} material={materials.Tile_3_0} />
      <mesh geometry={nodes.Tile_5.geometry} material={materials.Tile_5_0} />
      <mesh geometry={nodes.Tile_2_1.geometry} material={materials.Tile_2_0} />
      <mesh geometry={nodes.Tile_2_2.geometry} material={materials.Tile_2_1} />
      <mesh geometry={nodes.Tile_4_1.geometry} material={materials.Tile_4_0} />
      <mesh geometry={nodes.Tile_4_2.geometry} material={materials.Tile_4_1} />
      <mesh geometry={nodes.Tile_4_3.geometry} material={materials.Tile_4_2} />
    </group>
  )
}

useGLTF.preload('/t1_5.glb')
