/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t21_25.glb --transform 
Files: t21_25.glb [191.23MB] > t21_25-transformed.glb [15.83MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T21_25(props) {
  const { nodes, materials } = useGLTF('/t21_25-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_21.geometry} material={materials.Tile_21_0} />
      <mesh geometry={nodes.Tile_22.geometry} material={materials.Tile_22_0} />
      <mesh geometry={nodes.Tile_23.geometry} material={materials.Tile_23_0} />
      <mesh geometry={nodes.Tile_24.geometry} material={materials.Tile_24_0} />
      <mesh geometry={nodes.Tile_25.geometry} material={materials.Tile_25_0} />
    </group>
  )
}

useGLTF.preload('/t21_25-transformed.glb')
