/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t25_30.glb --transform 
Files: t25_30.glb [319.67MB] > t25_30-transformed.glb [26.87MB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T25_30(props) {
  const { nodes, materials } = useGLTF('/t25_30-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_26.geometry} material={materials.Tile_26_0} />
      <mesh geometry={nodes.Tile_28.geometry} material={materials.Tile_28_0} />
      <mesh geometry={nodes.Tile_30.geometry} material={materials.Tile_30_0} />
      <mesh geometry={nodes.Tile_27_1.geometry} material={materials.Tile_27_0} />
      <mesh geometry={nodes.Tile_27_2.geometry} material={materials.Tile_27_1} />
      <mesh geometry={nodes.Tile_29_1.geometry} material={materials.Tile_29_0} />
      <mesh geometry={nodes.Tile_29_2.geometry} material={materials.Tile_29_1} />
    </group>
  )
}

useGLTF.preload('/t25_30-transformed.glb')
