/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t6_10.glb --transform 
Files: t6_10.glb [356.57MB] > t6_10-transformed.glb [31.88MB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T6_10(props) {
  const { nodes, materials } = useGLTF('/t6_10-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_6.geometry} material={materials.Tile_6_0} />
      <mesh geometry={nodes.Tile_7.geometry} material={materials.Tile_7_0} />
      <mesh geometry={nodes.Tile_10.geometry} material={materials.Tile_10_0} />
      <mesh geometry={nodes.Tile_8_1.geometry} material={materials.Tile_8_0} />
      <mesh geometry={nodes.Tile_8_2.geometry} material={materials.Tile_8_1} />
      <mesh geometry={nodes.Tile_9_1.geometry} material={materials.Tile_9_0} />
      <mesh geometry={nodes.Tile_9_2.geometry} material={materials.Tile_9_1} />
    </group>
  )
}

useGLTF.preload('/t6_10-transformed.glb')
