/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 t7_10.glb --transform 
Files: t7_10.glb [341.28MB] > t7_10-transformed.glb [30.71MB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function T1_7(props) {
  const { nodes, materials } = useGLTF('/t7_10-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tile_7.geometry} material={materials.Tile_7_0} position={[15.9, 11.045, -10.076]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <group position={[11.16, 23.032, -12.968]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Tile_8_1.geometry} material={materials.Tile_8_0} />
        <mesh geometry={nodes.Tile_8_2.geometry} material={materials.Tile_8_1} />
      </group>
      <group position={[9.515, 35.801, -11.81]} rotation={[Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Tile_9_1.geometry} material={materials.Tile_9_0} />
        <mesh geometry={nodes.Tile_9_2.geometry} material={materials.Tile_9_1} />
      </group>
      <mesh geometry={nodes.Tile_10.geometry} material={materials.Tile_10_0} position={[9.187, 47.821, -8.788]} rotation={[Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/t7_10-transformed.glb')
