/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 midPoint4.glb --transform 
Files: midPoint4.glb [452.22KB] > midPoint4-transformed.glb [121.52KB] (73%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function MidPoint4(props) {
  const { nodes, materials } = useGLTF('/midPoint4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={(e) => {
          console.log(e.point)
        }}
        geometry={nodes.Tile_30001.geometry}
        material={materials.Tile_30_1}
        position={[0, -70, 0]}>
        {/* <meshPhongMaterial color={new THREE.Color('red')} shininess={0} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/midPoint4-transformed.glb')
