/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 midPoint1.glb --transform 
Files: midPoint1.glb [479.76KB] > midPoint1-transformed.glb [114.8KB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function MidPoint1() {
  const { nodes, materials } = useGLTF('/midPoint1-transformed.glb')
  return (
    <group dispose={null}>
      <mesh
        onClick={(e) => {
          // showPopup(image_filename, problemAreaId)
          console.log(e.point)
        }}
        geometry={nodes.Tile_8001.geometry}
        material={materials.Tile_8_0}
        position={[0, -70, 0]}>
        {/* <meshPhongMaterial color={new THREE.Color('black')} shininess={0} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/midPoint1-transformed.glb')
