/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 midPoint5.glb --transform 
Files: midPoint5.glb [522.89KB] > midPoint5-transformed.glb [133.02KB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function MidPoint5() {
  const { nodes, materials } = useGLTF('/midPoint5-transformed.glb')
  return (
    <group dispose={null}>
      <mesh
        onClick={(e) => {
          console.log(e.point)
        }}
        geometry={nodes.Tile_30002.geometry}
        material={materials.Tile_30_0}
        position={[0, -70, 0]}>
        <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/midPoint5-transformed.glb')
