/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 midPoint3.glb --transform 
Files: midPoint3.glb [477.66KB] > midPoint3-transformed.glb [112.27KB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function MidPoint2(props) {
  const { nodes, materials } = useGLTF('/midPoint3-transformed.glb')
  return (
    <group dispose={null}>
      <mesh
        onClick={(e) => {
          console.log(e.point)
        }}
        geometry={nodes.Tile_25001.geometry}
        material={materials.Tile_25_0}
        position={[0, -70, 0]}>
        {/* <meshPhongMaterial color={new THREE.Color('red')} shininess={0} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/midPoint3-transformed.glb')
