/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass8.glb --output ./jsx/glass8.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass8.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-16.294, 17.695, 9.467]} rotation={[Math.PI / 2, 0, Math.PI / 3]}>
        <mesh geometry={nodes.glass007_1.geometry} material={materials['material_0.015']} />
        <mesh geometry={nodes.glass007_2.geometry} material={materials['material_1.015']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass8.glb')
