/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass2.glb --output ./jsx/glass2.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-23.192, 10.731, 19.255]} rotation={[Math.PI / 2, 0, -0.908]}>
        <mesh geometry={nodes.glass001_1.geometry} material={materials['material_0.009']} />
        <mesh geometry={nodes.glass001_2.geometry} material={materials['material_1.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass2.glb')
