/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass10.glb --output ./jsx/glass10.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass10.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-22.314, 20.223, 19.491]} rotation={[Math.PI / 2, 0, -0.89]}>
        <mesh geometry={nodes.glass009_1.geometry} material={materials['material_0.017']} />
        <mesh geometry={nodes.glass009_2.geometry} material={materials['material_1.017']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass10.glb')
