/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass1.glb --output ./jsx/glass1.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-23.546, 10.726, 15.729]} rotation={[Math.PI / 2, 0, -0.471]}>
        <mesh geometry={nodes.glass_1.geometry} material={materials['material_0.008']} />
        <mesh geometry={nodes.glass_2.geometry} material={materials['material_1.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass1.glb')
