/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass9.glb --output ./jsx/glass9.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass9.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-23.078, 20.352, 15.009]} rotation={[Math.PI / 2, 0, -Math.PI / 9]}>
        <mesh geometry={nodes.glass008_1.geometry} material={materials['material_0.016']} />
        <mesh geometry={nodes.glass008_2.geometry} material={materials['material_1.016']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass9.glb')
