/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass3.glb --output ./jsx/glass3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-14.624, 20.197, 23.875]} rotation={[Math.PI / 2, 0, -2.199]}>
        <mesh geometry={nodes.glass002_1.geometry} material={materials['material_0.010']} />
        <mesh geometry={nodes.glass002_2.geometry} material={materials['material_1.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass3.glb')
