/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass12.glb --output ./jsx/glass12.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass12.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-11.775, 20.23, 11.291]} rotation={[Math.PI / 2, 0, 1.745]}>
        <mesh geometry={nodes.glass012_1.geometry} material={materials['material_0.020']} />
        <mesh geometry={nodes.glass012_2.geometry} material={materials['material_1.020']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass12.glb')
