/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass14.glb --output ./jsx/glass14.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass14.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-11.674, 22.753, 11.526]} rotation={[Math.PI / 2, 0, 1.763]}>
        <mesh geometry={nodes.glass013_1.geometry} material={materials['material_0.021']} />
        <mesh geometry={nodes.glass013_2.geometry} material={materials['material_1.021']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass14.glb')
