/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./opt/glass4.glb --output ./jsx/glass4.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glass4.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-19.954, 20.175, 22.314]} rotation={[Math.PI / 2, 0, -1.501]}>
        <mesh geometry={nodes.glass003_1.geometry} material={materials['material_0.011']} />
        <mesh geometry={nodes.glass003_2.geometry} material={materials['material_1.011']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glass4.glb')
