/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 main_window.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/main_window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001002.geometry} material={materials.Material__43} position={[-13.318, 18.389, -8.0]} rotation={[0.02, 1.23, -0.027]} scale={[0.2, 0.021, 0.154]} />
    </group>
  )
}

useGLTF.preload('/main_window.glb')
