/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 main_window.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/main_window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001002.geometry} material={materials.Material__43} position={[9.400, 16.5, -15.0]} rotation={[0.03, 1.23, -0.027]} scale={[0.282, 0.071, 0.001]} />
    </group>
  )
}

useGLTF.preload('/main_window.glb')
