/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 main_window.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/main_window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001002.geometry} material={materials.Material__43} position={[-10.5, 9.389, -25.5]} rotation={[0.02, 1.23, -0.027]} scale={[0.36, 0.040, 0.001]} />
    </group>
  )
}

useGLTF.preload('/main_window.glb')
