/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 1.glb --transform
Files: 1.glb [4.54MB] > 1-transformed.glb [1.47MB] (68%)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { modelPath } from './config'

export function ProblemAreas({ showPopup, glb_filename, image_filename, mesh_name, material_name, problemAreaIdx }) {
  const { nodes, materials } = useGLTF(`/${modelPath}/` + glb_filename)

  useEffect(() => {
    console.log('threejs:', nodes)
    // console.log('image_filename!!:', image_filename)
    // console.log('problemAreaIdx!!:', problemAreaIdx)

  }, [])

  return (
    <group dispose={null}>
      <mesh
        onClick={(e) => {


          console.log('problemAreaIdx : ', problemAreaIdx)
          showPopup(image_filename, problemAreaIdx)
          console.log(e.point)
        }}
        geometry={nodes[mesh_name].geometry}
        material={materials[material_name]}>
        <meshPhongMaterial color={new THREE.Color('red')} shininess={0} />
      </mesh>
    </group>
  )
}
